### ISSUE TITLE
Work progress

### ISSUE THREAD

**Issue by miguelc3** [miguelc3/TestAssignment2#2]
The color_segmented.py file is almost done, I just need to find a way to print the changes every time that a trackbar is moved.
The ar_pait.py file: already receives the json file; the segmentation is done; the selection of the largest object is also done.
Things to do: find the centroid of the largest object; create a white sheet to draw ...

**Comment by Kazadhum** [comment]
Will get on it tomorrow! Today I still have to prepare some things for Servomechanisms tomorrow, sadly

**Comment by GabrieleMicheli** [comment]
Thank you Miguel, I could start tomorrow and continue with the work you did!

**Comment by miguelc3** [comment]
ok then, I think maybe on friday I'll work on the assignment a litle more so, as soon as on of you upgarde something on the script make sure you update it here on git hub as well please xD

**Comment by miguelc3** [comment]
I think everything is working fine, expect advanced functionalities
On the color_segmenter.py file I couldn't yet print something every time the user change the value of one trackbar

**Comment by Kazadhum** [comment]
Just got through that error I had last night, so I'm picking it up now, I'll try and sort that problem out now

**Comment by Kazadhum** [comment]
Hold on, is it supposed to print something everytime the user changes the value of a trackbar? I don't think so, right?
"e o programa deverá, quando se alteram aqueles valores, mostrar de imediato o resultado da segmentação usando os novos limites." - I think this is referring to showing the mask

**Comment by miguelc3** [comment]
Yes, you're right.
But I noticed that, in the example video, a message was printed each time the teacher set a new value.
But I think it's not a priority right now, maybe in the end we'll try to do that.
